# .travis.yml
language: node_js
node_js:
    - "0.12"
addons:
  postgresql: "9.4"
notifications:
    slack: healthsamurai:lKl1jXV360NHMSzV2nwndkOv

before_script:
  - sudo apt-get install postgresql-contrib-9.4 postgresql-9.4-plv8  -qq -y
  - npm install && cd plpl && npm install

script: node_modules/mocha/bin/mocha --compilers mocha --compilers coffee:coffee-script/register spec/**/*coffee
