language: node_js
sudo: required
services:
- docker
node_js:
- '6'
addons:
  apt:
    packages:
    - python-pip
env:
  global:
  - secure: OhbEMmdvXwMoNsQCzWRIQsYc6LwcRAARjAoVv150LRTDB4s/FPo/67DQuUkcMJPp5+HyGh2/9giNArmn7NcMiXHtiUZKQKRkt758Ga9IdYidHJrmUI3wZKJns6W7SeCr4GSsd7cVcDo/ubFQQGZK2yIlRRF3zmWnEcPt9uLIlyJlrBu5DKUev65n/AdUzaqGf48efavz97A9DCVxwuE44jGp5Bqjoqqrben97j9U5L8A3APGIcweBaxcLQPunIZboA9DX8xrP/Y+C0cTJlJksbEb8jDNwrK+xLmX/Bd3o5fQh83/wyu2c/E9WrOR96e74VutLjXhdt5gOfzD79Q09lPziYg+0PkR8NaBwHldpmzRf75asem83OYGlNDacd2dkyiuqCNpa1xOIutdk9IKl0FNCn5C4OYFXaR6vPNwwZWF4lt+cXXs0il2/buWkR1Ydt35W1j0LHAPLezrrD839klfxHmVd+3BEf1RB9TQGMzSseSdMEsx5pWJh1k3gM/QGTRpjeaTat49oHEusSx6P+nU5L1VzfPN60/QJvkiS9ay0xdounbb9pkiI/oYyzQP5JD+dqKqxpBWEEBfhrxc+GhFZEJLPLW9XB9dBF5FCWRVweGyDcGa2SP81xV7L/Vc56jWsKcA/KkCLnpSgBm+b34Fg45VOga1zO2lxEV/Cdk=
  - secure: TCYwHystRMTz1AKWfQ7436LM7r2WumYQNaLs3f/j4QLZEZhZJMTUGClYzfc80mbjkcpSsbXcitSOfwLxo+aTG8kgvQTVFZJsNNExinnlZ8zo8h91+iyN4GHdEECFnylEAC1QvSUJbACpYTmHwz5HsXrBmrP5yKVloesbbdTr5V34Z9DhKHb6MkpgNzzYM7Cy977eqkp5CaFOwRy1CbxM2bCJrgZEFrBGpW9Iqb5YLMoorygffDWltNZ/GK39hYsETOpdNkUIPZWbGQyRx4yYpydk4AMEBz7r0QM6opf4YVCoA2MfrbDnPGrfyyv+T1NgYmBa4PYzpBOACphuYmVcM6Voqb3qxZUxTzQ4lTsNU/gZ8kUQdlbjQCtVotj5blp39ynmOCt6F9iKXGPAG3u8iWB19+19CvpeFirxwa5yG6b0rlsnZNAyQYi+2/7mxR1ZDZjl2llX4WmVPM0NHQ+yfMIrljdog+2SkNOO0PPBcfba4inZE8A7+k/8zCucBOofxx0zfam44FjisUtiVjpEFJtKmEMHznKN/AlEu0SmUl859Hc+418xBboxYr5lux9d+ha0QD4/bpokRNFvSM3ZGcBP44+m3bRpyvjuv+cMN7DBedn2QeBJSnfsB0cJNepoi++b7NsZLggTqKy7KhvGplapiYvQrWSys6ZPnq28PXA=
  - secure: B8Mc7dg0VDL8DZ0L2HakGWlzHnMprVtihjwcmn0a02mhaTxFv1FCXsb3O0pB/kQ0M5Ox2OzLSyrMUZFK+aiY1jhDJrllbXBRa34fVEawUdnczjzmqm8sWyfT3tTPwVPcdLSXuGPwLXmjOBnlJth1zBwJcDK6R4Epv80tNsViG8fmXk23zjS+shi4utlbScuZLZ9jM9DHay7IyMsVDxCSq7Gjsukue8ib3hzxGrL0a/anWfFo+9N7uLwplacPo/Vt+crA9VlIUvfd3Oli1KaEB7GsTCZs2xFPc48oinchei2T/Kb7oB13YW+6T2QYiWEjCw5Y9OEA7G+Ic7KSRqNruUH/63xaBEeCmBKUw5pbg/OKXvHEbI68AlMTls/xEoCPXY52KFUBCJ5tws8MXlC5vdzotjAz+gcBDz3pbQEaEA+MeCz1j9ogRTQCJ7lxqK8zWO8z4HV2u0ZOZ0sHA5IrHuHwiuLNjZyHwneTS+ov889s5ChdChvObRbcLOXtfQUABhvz69zyX/5c8kfVmniQ+FfYNmskNCPoqJifiZESjTnGbgknfNyHeiH2+QHU7nkpQjzbNUpePbJv3hMWSyh4gDT2ky6rxikvaLmsXZLybmvLyiF733VeF2svNXraaJ8yTW6ss/rhfTdESXxMghalFV4Pk02jW2PzLaFND3RH7ZY=
  - secure: NWWpzf78Bfh6UIgzwBaZ+nEyCR6FWjVKdkTMKmF2FL/yClzgfc2dc5NOREzzvhnCx0nFcNQj+8ReCxbyvxjN3qMWWgX7VASTyb2Hdvv8DE4+3RtTeioQ+NDkG0lItgzfbxaomwq1Wu2ZonSwZdEwXDvn8Posr4VkZcDk5YAW6pXI36xqholoGHcF5rNaKmfcNTn5Vw30hVVp5NAigxWiTM5PGOQFSMq33xBOVV1jIUnFTQhzIcaj67U0x6Qz7ieMo7bBM1x+DuxuK17gb5wwrfCKL7pv4jAtxk/EUKkUHmTROFF3sX8EzsxkYK9O8dGXiVSoTleykBsqIxKQ8ITjrpI3GXGLY/Tr/u42gsoJFWMFxOUTbwjsBZEBgfauvm3AQmNTa7FXA5JESdfyAMg7Vr+Y/eigxzS7r6tqQMFydLIjDyIgE51RKWzrmohgiUCxkbDmvWxgr542wA38wvVOEo2XNKNUxiuF89Qdw8AZpzPneYz0Td7LyjhppFajsK2ldrZhOW7+M+kHzXTHMT0p9EYixQiISMGGsEybJnctlpdI71sWB7AmSaFcBGNSR0wxkDj3j0TXd1lPSvlhlrSWFm/5DqqRdauQfPN7Px1sjNTxq6BU2AWfnDC/8L6zwDtJ1IdBpkiCjTr0CFccIym1Q/Ouo6BHVqkG8UdM2O7KGCI=
  - secure: h6wEGTRrYfHwucN/H2j5mt0UbneFEhcL2oylaSJzq90f9N+XS6kcM5CF5iJQzLewyYnXvnEbAR1nOQVTPWmlBdpRcyfL4/gTv6j1Q2zQWWuOt+91Gsi8a6yjZHH+PBd1F/og3IVtWbcl4zzhdswxjTuvmaWrPfyQPGza1e6oTxGNnoOTWcHIvX8fEiyDw0pLsUz+f8AM7nzXPpTI3vIcZarmLzKEpQRPnFXQ/uXm1aYWD0hRhjDp9U8l/BseN1Zs9GdvVmd5DcgFZx+NwXqzIbKrc8LOsBsIwe1Pm5NXHtwjCJPlk+/Yjc+E7hcrcGE8IximRLweRqJDH4verd9nmvVAKO+ZE0XJq0FdAGJ4q3QPXWV3/wqukdd/DL7ApoToCmxVesSqZz/kKN8UhRpMWq2mYJQGNhQDL5BxORG5vjJQr6Fm7JfHATGpvkaPqqu+rn5c3nnZYoE+4CRffaDhESim8cwKEY0i7h6ROsft/WywJt6I1fN03b/J6xg73K8JmVEZTZlC1s1IpotF0AqietFAWHjiJH6TGwuK+LBoIOEOHIiP81wrYdaKXT3qgVp2c8W/UAByEro5U54SZ4zDkVkAytxi2kmhO7JH+LXJdBGFjb+TU/gsaT6i/jAclH2CejgXJUIkeCi+AfmuD5Uhfa2Bs2n3neK7qsZ4R6pGiSs=
  matrix:
  - PLV8_VERSION=1.4.3 SCHEMAS="public"
  - PLV8_VERSION=1.4.4 SCHEMAS="public"
  - PLV8_VERSION=1.4.7 SCHEMAS="foo bar"
  # Unfortunately plv8 1.5.x hard to install because required very new libv8 version <https://github.com/plv8/plv8/issues/158#issuecomment-189621200>.
notifications:
  slack: fhirbase:isitOv0KvPgaMzrccuAzVUwB
before_install:
- |
  cd $TRAVIS_BUILD_DIR || exit 1
  docker build --tag=fhirbase-tests-in-schemas:pg-9.4-plv8-$PLV8_VERSION \
               --file=Dockerfile-pg-9.4-plv8-$PLV8_VERSION ./ || exit 1
script: |
  docker run --name=fhirbase-tests-in-schemas \
             fhirbase-tests-in-schemas:pg-9.4-plv8-$PLV8_VERSION \
             --schemas="$SCHEMAS" --install-fhirbase || exit 1
after_success: |
  if [ "$PLV8_VERSION" == "1.4.7" ]; then
    docker cp fhirbase-tests-in-schemas:/home/fhirbase/fhirbase/build \
              $TRAVIS_BUILD_DIR/ || exit 1
    AWS_DEFAULT_REGION=us-west-1 \
      AWS_SECRET_ACCESS_KEY=$BUILD_AWS_SECRET_ACCESS_KEY \
      AWS_ACCESS_KEY_ID=$BUILD_AWS_ACCESS_KEY_ID \
      aws s3 cp --recursive $TRAVIS_BUILD_DIR/build s3://fhirbase
  fi
  if [ "$PLV8_VERSION" == "1.4.7" ] && [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo $PASS | gpg --passphrase-fd 0 --decrypt --output - ./secure.tar.gz.asc \
      | tar --extract --gzip --file -
    [[ ${PIPESTATUS[0]} -ne 0 || ${PIPESTATUS[1]} -ne 0 ]] && exit 1
    pip install --user --upgrade 'ansible<2' || exit 1
    pip install --user --upgrade boto || exit 1
    cd perf/provisioning || exit 1
    export ANSIBLE_HOST_KEY_CHECKING=False || exit 1
    python2 ~/.local/bin/ansible-playbook \
            --inventory-file=inventories/ec2 \
            ec2_start.yml || exit 1
    python2 ~/.local/bin/ansible-playbook \
            --private-key=../../secure/fhirbase_performance_benchmark.pem \
            --inventory-file=inventories/ec2.py \
            --user=ubuntu \
            bootstrap.yml || exit 1
    python2 ~/.local/bin/ansible-playbook \
            --private-key=../../secure/fhirbase_performance_benchmark.pem \
            --inventory-file=inventories/ec2.py \
            --user=ubuntu \
            --extra-vars="timestamp=foobar" \
            perf.yml || exit 1
  fi
