language: node_js
sudo: true
node_js:
- '0.12'
addons:
  postgresql: 9.4
  apt:
    packages:
    - build-essential
    - libv8-dev
    - postgresql-contrib-9.4
    - postgresql-server-dev-9.4
    - python-pip
env:
  global:
  - secure: OhbEMmdvXwMoNsQCzWRIQsYc6LwcRAARjAoVv150LRTDB4s/FPo/67DQuUkcMJPp5+HyGh2/9giNArmn7NcMiXHtiUZKQKRkt758Ga9IdYidHJrmUI3wZKJns6W7SeCr4GSsd7cVcDo/ubFQQGZK2yIlRRF3zmWnEcPt9uLIlyJlrBu5DKUev65n/AdUzaqGf48efavz97A9DCVxwuE44jGp5Bqjoqqrben97j9U5L8A3APGIcweBaxcLQPunIZboA9DX8xrP/Y+C0cTJlJksbEb8jDNwrK+xLmX/Bd3o5fQh83/wyu2c/E9WrOR96e74VutLjXhdt5gOfzD79Q09lPziYg+0PkR8NaBwHldpmzRf75asem83OYGlNDacd2dkyiuqCNpa1xOIutdk9IKl0FNCn5C4OYFXaR6vPNwwZWF4lt+cXXs0il2/buWkR1Ydt35W1j0LHAPLezrrD839klfxHmVd+3BEf1RB9TQGMzSseSdMEsx5pWJh1k3gM/QGTRpjeaTat49oHEusSx6P+nU5L1VzfPN60/QJvkiS9ay0xdounbb9pkiI/oYyzQP5JD+dqKqxpBWEEBfhrxc+GhFZEJLPLW9XB9dBF5FCWRVweGyDcGa2SP81xV7L/Vc56jWsKcA/KkCLnpSgBm+b34Fg45VOga1zO2lxEV/Cdk=
  - secure: TCYwHystRMTz1AKWfQ7436LM7r2WumYQNaLs3f/j4QLZEZhZJMTUGClYzfc80mbjkcpSsbXcitSOfwLxo+aTG8kgvQTVFZJsNNExinnlZ8zo8h91+iyN4GHdEECFnylEAC1QvSUJbACpYTmHwz5HsXrBmrP5yKVloesbbdTr5V34Z9DhKHb6MkpgNzzYM7Cy977eqkp5CaFOwRy1CbxM2bCJrgZEFrBGpW9Iqb5YLMoorygffDWltNZ/GK39hYsETOpdNkUIPZWbGQyRx4yYpydk4AMEBz7r0QM6opf4YVCoA2MfrbDnPGrfyyv+T1NgYmBa4PYzpBOACphuYmVcM6Voqb3qxZUxTzQ4lTsNU/gZ8kUQdlbjQCtVotj5blp39ynmOCt6F9iKXGPAG3u8iWB19+19CvpeFirxwa5yG6b0rlsnZNAyQYi+2/7mxR1ZDZjl2llX4WmVPM0NHQ+yfMIrljdog+2SkNOO0PPBcfba4inZE8A7+k/8zCucBOofxx0zfam44FjisUtiVjpEFJtKmEMHznKN/AlEu0SmUl859Hc+418xBboxYr5lux9d+ha0QD4/bpokRNFvSM3ZGcBP44+m3bRpyvjuv+cMN7DBedn2QeBJSnfsB0cJNepoi++b7NsZLggTqKy7KhvGplapiYvQrWSys6ZPnq28PXA=
  matrix:
  - PLV8_VERSION=v1.4.4
notifications:
  slack: fhirbase:isitOv0KvPgaMzrccuAzVUwB
before_install:
- openssl aes-256-cbc
  -K $encrypted_6ab70d4cdf06_key
  -iv $encrypted_6ab70d4cdf06_iv
  -in perf/provisioning/secure/secure.tar.gz.enc
  -out perf/provisioning/secure/secure.tar.gz
  -d
- |
  cd /tmp || exit 1
  git clone https://github.com/plv8/plv8.git || exit 1
  cd /tmp/plv8 || exit 1
  git checkout $PLV8_VERSION || exit 1
  sudo make all install || exit 1
before_script:
- cd $TRAVIS_BUILD_DIR
- npm install && cd plpl && npm install
- npm install -g mocha && npm install -g coffee-script
- psql -c "CREATE USER fb WITH PASSWORD 'fb'"
- psql -c 'ALTER ROLE fb WITH SUPERUSER'
- psql -c 'CREATE DATABASE fhirbase;' -U postgres
- psql -c '\dt' -U postgres
- cd ..
script: |
  export DATABASE_URL=postgres://fb:fb@localhost:5432/fhirbase || exit 1
  export TRAVIS=true || exit 1
  FB_SCHEMA=foo ./build.sh || exit 1
  { echo "CREATE SCHEMA IF NOT EXISTS foo; SET search_path TO foo;" \
    && cat tmp/build.sql ; } \
    | psql fhirbase
  [[ ${PIPESTATUS[0]} -ne 0 || ${PIPESTATUS[1]} -ne 0 ]] && exit 1
  FB_SCHEMA=foo npm run test || exit 1
  FB_SCHEMA=bar ./build.sh || exit 1
  { echo "CREATE SCHEMA IF NOT EXISTS bar; SET search_path TO bar;" \
    && cat tmp/build.sql ; } \
    | psql fhirbase
  [[ ${PIPESTATUS[0]} -ne 0 || ${PIPESTATUS[1]} -ne 0 ]] && exit 1
  FB_SCHEMA=bar npm run test || exit 1
after_success: |
  if [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    cat perf/provisioning/secure/secure.tar.gz \
        | tar --extract --gzip --directory perf/provisioning/secure --file -
    [[ ${PIPESTATUS[0]} -ne 0 || ${PIPESTATUS[1]} -ne 0 ]] && exit 1
    pip install --user --upgrade 'ansible<2' || exit 1
    pip install --user --upgrade boto || exit 1
    cd perf/provisioning || exit 1
    export ANSIBLE_HOST_KEY_CHECKING=False || exit 1
    python2 ~/.local/bin/ansible-playbook \
            --inventory inventories/ec2 \
            ec2_start.yml || exit 1
    python2 ~/.local/bin/ansible-playbook \
            --private-key=secure/fhirbase_performance_benchmark.pem \
            --inventory=inventories/amazon \
            bootstrap.yml || exit 1
    python2 ~/.local/bin/ansible-playbook \
            --private-key=secure/fhirbase_performance_benchmark.pem \
            --inventory=inventories/amazon \
            --extra-vars="timestamp=foobar" \
            perf.yml || exit 1
  fi
