# .travis.yml
addons:
  postgresql: "9.4"

#before_script:
#- sudo su $USER -c "source ./cfg/travis_cfg.sh && ./install-postgres"

script: sudo su $USER -c "env PGUSER=postgres DB=test ./runme integrate"
after_success: ./script/release.sh
