# .travis.yml
language: node_js
node_js:
    - "0.12"
addons:
  postgresql: "9.4"
notifications:
    slack: healthsamurai:lKl1jXV360NHMSzV2nwndkOv

before_script:
  - sudo apt-get install postgresql-contrib-9.4 postgresql-9.4-plv8  -qq -y
  - npm install && cd plpl && npm install
  - npm install -g mocha && npm install -g coffee-script

script: npm test
