- hosts: app
  gather_facts: True
  tasks:

  - name: Backup PostgreSQl log file
    shell: cp "{{ postgres.log }}" "{{ postgres.log }}_{{ timestamp }}"
    sudo_user: "{{ postgres.system_user }}"

  - name: Truncate PostgreSQl log file
    shell: echo > "{{ postgres.log }}"
    sudo_user: "{{ postgres.system_user }}"

  - name: PostgreSQl restart
    service: name=postgresql state=restarted
    sudo_user: root

  - name: Clone Fhirbase project
    git:
    args:
      accept_hostkey: yes
      dest: "{{ fhirbase.app_dir }}/"
      force: yes
      key_file: "{{ os.user.home }}/.ssh/fhirbase_performance_benchmark.pem"
      repo: git@github_fhirbase_plv8:fhirbase/fhirbase-plv8.git
      track_submodules: yes
      update: yes
      version: "{{ git.branch }}"
    sudo_user: "{{ os.user.name }}"

  - name: Clone Fhirbase documentation project
    git:
    args:
      accept_hostkey: yes
      dest: "{{ fhirbase.doc_dir }}/"
      force: yes
      key_file: "{{ os.user.home }}/.ssh/fhirbase_performance_documentation"
      repo: git@github_fhirbase_documentation:fhirbase/fhirbase.github.io.git
      track_submodules: yes
      update: yes
      version: "{{ git.branch }}"
    sudo_user: "{{ os.user.name }}"

  - name: Daemonizing Fhirbase performance tests and not waiting for exit
    shell:
      su {{ os.user.name }}
      --shell=/bin/bash
      --command="{{ fhirbase.app_dir }}/perf/perf
      --createdb
      --dropdb
      --number-of-patients=1000
      --pgdatabase={{ postgres.database }}
      --pgpassword={{ postgres.password }}
      --pguser={{ postgres.user }}
      --verbose=3"
      && cp "{{ postgres.log }}" "{{ fhirbase.app_dir }}/perf/perf.log"
      && chown "{{ os.user.name }}":"{{ os.user.name }}" "{{ fhirbase.app_dir }}/perf/perf.log"
      && su {{ os.user.name }}
      --shell=/bin/bash
      --command="cd {{ fhirbase.app_dir }}
      && git add perf/perf.log
      && git commit --message='{{ git.commit.message }}'
      && git push origin {{ git.branch }}"
      ; shutdown -h now
    async: 900
    poll: 0
    sudo_user: root
