- hosts: app
  gather_facts: True
  tasks:

  - name: Clone Fhirbase project
    git:
    args:
      accept_hostkey: yes
      dest: "{{ app_dir }}/"
      force: yes
      key_file: "{{ home }}/.ssh/fhirbase_performance_benchmark.pem"
      repo: git@github.com:fhirbase/fhirbase-plv8.git
      track_submodules: yes
      update: yes
      version: "{{ git.branch }}"
    sudo_user: "{{ user }}"

  - name: PostgreSQl should log all statements
    lineinfile: dest="{{ postgres.conf }}" line="log_statement = 'all'"
    sudo_user: "{{ postgres.system_user }}"

  - name: PostgreSQl should log statements with any durations
    lineinfile: dest="{{ postgres.conf }}" line="log_min_duration_statement = 0"
    sudo_user: "{{ postgres.system_user }}"

  - name: Backup PostgreSQl log file
    shell: cp "{{ postgres.log }}" "{{ postgres.log }}_{{ timestamp }}"
    sudo_user: "{{ postgres.system_user }}"

  - name: Truncate PostgreSQl log file
    shell: echo > "{{ postgres.log }}"
    sudo_user: "{{ postgres.system_user }}"

  - name: PostgreSQl restart
    service: name=postgresql state=restarted
    sudo_user: root

  - name: Daemonizing Fhirbase performance tests and not waiting for exit
    shell:
      su {{ user }}
      --shell=/bin/bash
      --command="{{ app_dir }}/perf/perf
      --createdb
      --dropdb
      --number-of-patients=1000
      --pgdatabase={{ postgres.database }}
      --pgpassword={{ postgres.password }}
      --pguser={{ postgres.user }}
      --verbose=3"
      && cp "{{ postgres.log }}" "{{ app_dir }}/perf/perf.log"
      && chown "{{ user }}":"{{ user }}" "{{ app_dir }}/perf/perf.log"
      && su {{ user }}
      --shell=/bin/bash
      --command="cd {{ app_dir }}
      && git add perf/perf.log
      && git commit --message='{{ git.commit.message }}'
      && git push origin {{ git.branch }}"
    async: 900
    poll: 0
    sudo_user: root
