- hosts: app
  gather_facts: True
  tasks:

  - name: Clone Fhirbase project
    git:
    args:
      accept_hostkey: yes
      dest: "{{ app_dir }}/"
      force: yes
      key_file: "{{ home }}/key/deployer_rsa"
      repo: git@github.com:fhirbase/fhirbase-plv8.git
      track_submodules: yes
      update: yes
      version: perf
    sudo_user: "{{ user }}"

  - name: PostgreSQl should log all statements
    lineinfile: dest="{{ postgresql.conf }}" line="log_statement = 'all'"

  - name: PostgreSQl should log statements with any durations
    lineinfile: dest="{{ postgresql.conf }}" line="log_min_duration_statement = 0"

  - name: Backup PostgreSQl log file
    shell: cp "{{ postgresql.log }}" "{{ postgresql.log }}_{{ timestamp }}"
    sudo_user: postgres

  - name: Truncate PostgreSQl log file
    shell: echo > "{{ postgresql.log }}"
    sudo_user: postgres

  - name: PostgreSQl restart
    service: name=postgresql state=restarted
    sudo_user: root

  - name: Daemonizing Fhirbase performance tests and not waiting for exit
    shell:
      ./perf
      --createdb
      --dropdb
      --number-of-patients=1000
      --pgdatabase={{ postgres.database }}
      --pgpassword={{ postgres.password }}
      --pguser={{ postgres.user }}
      --verbose=3
      ; cp "{{ postgresql.log }}" "{{ app_dir }}/perf/perf.log"
      && chown "{{ user }}":"{{ user }}" "{{ app_dir }}/perf/perf.log"
    async: 900
    poll: 0
    args:
      chdir: "{{ app_dir }}/perf"
    sudo_user: root
